GET http://localhost:5000/api/users

###
POST http://localhost:5000/api/auth/login
Content-Type: "application/json"

{
    "email": "aaa",
    "password": "aaa2"
}

###
GET http://localhost:5000/api/users
# Authorization: Bearer